name: Terraform Destroy

# Dispatch means it requires manual confirmation to destroy the resource
on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: "Type 'destroy' to confirm"
        required: true
        default: ''

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash
          working-directory: ./infrastructure


    steps:

     # Connect to Tailscale to gain access to Vault
    - name: Connect to Tailnet
      uses: tailscale/github-action@v3
      with: 
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }} # uses the GH secrets 
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:ci

     # Fetch Aws secrets from Vault
    - name: Import secrets from Vault
      uses: hashicorp/vault-action@v3
      with:
        # vault node/IP
        url: https://vault.waifuprotect.org
        method: "jwt" # JSON web token is an industry-standard signed digital ID card for GH Actions
        role: "github-actions"
        secrets: |
          secret/data/terraform/aws AWS_ACCESS_KEY_ID | AWS_ACCESS_KEY_ID ;
          secret/data/terraform/aws AWS_SECRET_ACCESS_KEY | AWS_SECRET_ACCESS_KEY

    - name: Checkout
      uses: actions/checkout@v4
    
    - name: setup-terraform
      uses: hashicorp/setup-terraform 

    - name: Terraform init
      run: terraform init

    - name: Terraform Destroy
      if: ${{ inputs.confirm_destroy == 'destroy' }}
      run: terraform destroy -auto-approve -input=false
